name: Update Douban

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas
      - name: Update CSV
        run: |
          python update_csv.py
      - name: Build and deploy site
        uses: actions/pages-build-deployment@1
